version: '2.2'
services: 

  api-service:
    build:
      dockerfile: ./Dockerfile
      context: ${BACKEND_PATH}
    image:  pdv
    container_name: ${API_NAME}
    command: bash -c "npm i && npm start"
    user: root
    environment:
      - TZ=$TZ
      - NODE_ENV=development
    working_dir: /app
    restart: unless-stopped
    ports: 
      - 3355:3355
    volumes: 
      - ${BACKEND_PATH}:/app