version: '3.3'
services: 

  api-service:
    build:
      dockerfile: ./api-server/Dockerfile
      context: ${BACKEND_PATH}
    image:  pdv
    container_name: ${API_NAME}
    command: bash -c "npm i && npm start"
    user: root
    environment:
      - TZ=$TZ
      - NODE_ENV=${NODE_ENV}
    working_dir: /app
    restart: unless-stopped
    depends_on: 
      - mysql
    ports: 
      - ${BACK_PORT}:3355
    volumes: 
      - ${BACKEND_PATH}:/app

  mysql:
      image: mysql:latest
      restart: always
      container_name: mysqldb
      environment:
        MYSQL_ROOT_PASSWORD: '123456'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'test'
      volumes:
        - ./db-data:/var/lib/mysql
        - ./entrypoint:/docker-entrypoint-initdb.d/
      ports:
        - "3306:3306"
      command: mysqld --init-file="/docker-entrypoint-initdb.d/create_data_base.sql"